- name: "facts.config: Gather config"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/config/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_config

- name: "facts.config: Recording content in tower_facts['config']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'config': reg_tower_facts_config.json }) }}"
