- name: "facts.instance_groups: Gather instance_groups"
  uri:
    url: "https://{{ ansible_tower_config.host }}/api/v2/instance_groups/"
    user: "{{ ansible_tower_config.username }}"
    password: "{{ ansible_tower_config.password }}"
    validate_certs: "{{ ansible_tower_config.verify_ssl|bool }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ ansible_tower_config.format }}"
  register: reg_tower_facts_instance_groups

- name: "facts.instance_groups: Recording content in ansible_tower_facts['instance_groups']"
  set_fact:
    ansible_tower_facts: "{{ ansible_tower_facts | combine({ 'instance_groups': reg_tower_facts_instance_groups.json.results }) }}"
