- name: "facts.instances: Gather instances"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/instances/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_instances

- name: "facts.instances: Recording content in tower_facts['instances']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'instances': reg_tower_facts_instances.json.results }) }}"
