- name: "facts.instance_groups: Gather instance_groups"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/instance_groups/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_instance_groups

- name: "facts.instance_groups: Recording content in tower_facts['instance_groups']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'instance_groups': reg_tower_facts_instance_groups.json.results }) }}"
