- name: "facts.inventories: Gather inventories"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/inventories/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_inventories

- name: "facts.inventories: Recording content in tower_facts['inventories']"
  set_fact:
    tower_facts: "{{  tower_facts | combine({ 'inventories': reg_tower_facts_inventories.json.results }) }}"
