- name: "facts.job_templates: Gather job_templates"
  uri:
    url: "https://{{ ansible_tower_config.host }}/api/v2/job_templates/"
    user: "{{ ansible_tower_config.username }}"
    password: "{{ ansible_tower_config.password }}"
    validate_certs: "{{ ansible_tower_config.verify_ssl|bool }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ ansible_tower_config.format }}"
  register: reg_tower_facts_job_templates

- name: "facts.job_templates: Recording content in ansible_tower_facts['job_templates']"
  set_fact:
    ansible_tower_facts: "{{  ansible_tower_facts | combine({ 'job_templates': reg_tower_facts_job_templates.json.results }) }}"
