- name: "facts.settings: Gather settings"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/settings/all/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_settings

- name: "facts.settings: Recording content in tower_facts['settings']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'settings': reg_tower_facts_settings.json }) }}"
