- name: "facts.teams: Gather teams"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/teams/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_teams

- name: "facts.teams: Recording content in tower_facts['teams']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'teams': reg_tower_facts_teams.json.results }) }}"
