- name: "facts.users: Gather users"
  uri:
    url: "https://{{ tower_config.host }}/api/v2/users/"
    user: "{{ tower_config.username }}"
    password: "{{ tower_config.password }}"
    validate_certs: "{{ tower_config.verify_ssl|bool }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: GET
    body_format: "{{ tower_config.format }}"
  register: reg_tower_facts_users

- name: "facts.users: Recording content in tower_facts['users']"
  set_fact:
    tower_facts: "{{ tower_facts | combine({ 'users': reg_tower_facts_users.json.results }) }}"
